# Generated by Django 5.0 on 2024-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_rename_real_estate_advertisementimage_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='sub_street',
            new_name='side_street',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='zone',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='province',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='map_position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
