# Generated by Django 5.0 on 2024-08-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_rename_sub_street_advertisement_side_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='meterage',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='mortgage_price',
            new_name='disposit',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='number_of_elevators',
            new_name='elevator',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='floor_number',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='total_number_of_floors',
            new_name='number_of_floors',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='number_of_parkings',
            new_name='parking',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='rent_price',
            new_name='rent',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='number_of_wcs',
            new_name='restroom',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='number_of_rooms',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='number_of_warehouses',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='wc_type',
            new_name='type_of_restroom',
        ),
    ]
