# Generated by Django 5.0 on 2024-08-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisement_flooring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='type_of_restroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_of_restroom', to='advertisements.advertisementchoice'),
        ),
    ]
