# Generated by Django 5.0 on 2024-08-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_alter_advertisement_type_of_restroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='disposit',
            new_name='desposit',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='buying_price',
        ),
    ]
