# Generated by Django 5.0 on 2024-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='desposit',
            new_name='deposit',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default='2024-08-07 12:20'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='modified_at',
            field=models.DateTimeField(default='2024-08-07 12:20'),
        ),
    ]
