# Generated by Django 5.0 on 2024-08-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_rename_desposit_advertisement_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default='2024-08-08 00:35'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='modified_at',
            field=models.DateTimeField(default='2024-08-08 00:35'),
        ),
    ]
