# Generated by Django 5.0 on 2024-08-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default='2024-08-08 01:07'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='modified_at',
            field=models.DateTimeField(default='2024-08-08 01:07'),
        ),
    ]
