# Generated by Django 5.0 on 2024-08-08 21:25

import common.utils.database
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0012_alter_advertisement_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=common.utils.database.formated_datetime_now),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='modified_at',
            field=models.DateTimeField(default=common.utils.database.formated_datetime_now),
        ),
        migrations.CreateModel(
            name='SavedAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=common.utils.database.formated_datetime_now)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
