# Generated by Django 5.0 on 2024-08-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0013_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=1000)),
                ('video_full_path', models.CharField(max_length=1000)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertisements.advertisement')),
            ],
        ),
    ]
