# Generated by Django 5.0 on 2024-09-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0017_remove_suggestedsearch_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedsearch',
            name='query',
            field=models.CharField(max_length=300),
        ),
    ]
