# Generated by Django 5.0 on 2024-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0019_rename_display_name_suggestedsearch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='buy',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='deposit',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rent',
            field=models.PositiveBigIntegerField(),
        ),
    ]
