# Generated by Django 5.0 on 2024-07-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('number', models.CharField(max_length=11)),
                ('landline_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('main_street', models.CharField(max_length=50)),
                ('sub_street', models.CharField(max_length=50)),
                ('score', models.FloatField(default=5)),
                ('number_of_active_ads', models.PositiveIntegerField(default=0)),
                ('number_of_comments', models.PositiveIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
