# Generated by Django 5.0 on 2024-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateoffice',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='image_full_path',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='instagram',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='linkedin',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='site',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='telegram',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
