# Generated by Django 5.0 on 2024-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_offices', '0003_realestateoffice_blue_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateoffice',
            name='bg_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='bg_image_full_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
