# Generated by Django 5.0 on 2024-08-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_offices', '0004_realestateoffice_bg_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestateoffice',
            old_name='instagram',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='realestateoffice',
            old_name='linkedin',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='realestateoffice',
            old_name='site',
            new_name='whatsapp',
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='email',
            field=models.CharField(default='amlak@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
