# Generated by Django 5.0 on 2024-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_offices', '0006_commentscorereason_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateoffice',
            name='score_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestateoffice',
            name='score_sum',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
