# Generated by Django 5.0 on 2024-08-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_offices', '0008_reportreason_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='real_estate_office',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, to='real_estate_offices.realestateoffice'),
            preserve_default=False,
        ),
    ]
