# Generated by Django 5.0 on 2024-08-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_offices', '0009_report_real_estate_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_reason',
            new_name='reason',
        ),
    ]
