# Generated by Django 5.0 on 2024-10-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_offices', '0010_rename_report_reason_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateoffice',
            name='score_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestateoffice',
            name='score_sum',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
