# Generated by Django 5.0 on 2024-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(default='t', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.CharField(default='t', max_length=50),
            preserve_default=False,
        ),
    ]
