# Generated by Django 5.0 on 2024-07-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_city_slug_province_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
