# Generated by Django 5.0 on 2024-07-05 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate_offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed_by_real_estate_office', models.BooleanField(default=False)),
                ('score', models.FloatField(default=5)),
                ('number_of_active_ads', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=11)),
                ('landline_number', models.CharField(max_length=50)),
                ('real_estate_office', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='real_estate_offices.realestateoffice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
