# Generated by Django 5.0 on 2024-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_real_estate_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
