# Generated by Django 5.0 on 2024-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='bg_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='realtor',
            name='bg_image_full_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
