# Generated by Django 5.0 on 2024-08-09 21:01

import common.utils.database
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=common.utils.database.formated_datetime_now),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=common.utils.database.formated_datetime_now),
        ),
    ]
