# Generated by Django 5.0 on 2024-08-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_comment_created_at_comment_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='score_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realtor',
            name='score_sum',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
