# Generated by Django 5.0 on 2024-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_realtor_score_num_realtor_score_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='email',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='facebook',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='telegram',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='twitter',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='whatsapp',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtor',
            name='score',
            field=models.FloatField(default=4),
        ),
    ]
