# Generated by Django 5.0 on 2024-08-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0008_realtor_email_realtor_facebook_realtor_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentScoreReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='realtor',
            name='blue_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='score_reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='realtors.commentscorereason'),
            preserve_default=False,
        ),
    ]
