# Generated by Django 5.0 on 2024-08-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0011_reportreason_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='realtor',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor'),
            preserve_default=False,
        ),
    ]
