# Generated by Django 5.0 on 2024-08-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0012_report_realtor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_reason',
            new_name='reason',
        ),
    ]
