# Generated by Django 5.0 on 2024-09-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('page', models.CharField(max_length=50, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
