# Generated by Django 5.0 on 2024-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0002_alter_mainpage_content_alter_mainpage_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='section',
            new_name='title',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='btn_text',
            field=models.CharField(default='tset', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='icon',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
