# Generated by Django 5.0 on 2024-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='special',
            field=models.IntegerField(default=0),
        ),
    ]
