# Generated by Django 5.0 on 2024-06-25 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='CreatedAt',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ModifiedAt',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 11, 4, 42, 743663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 11, 4, 42, 743687, tzinfo=datetime.timezone.utc)),
        ),
    ]
