# Generated by Django 5.0.6 on 2024-06-25 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 19, 7, 25, 992871, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 19, 7, 25, 992931, tzinfo=datetime.timezone.utc)),
        ),
    ]
