# Generated by Django 5.0 on 2024-06-26 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 21, 17, 12, 258890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 21, 17, 12, 258911, tzinfo=datetime.timezone.utc)),
        ),
    ]
