# Generated by Django 5.0 on 2024-07-06 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 9, 12, 0, 925547, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 9, 12, 0, 925567, tzinfo=datetime.timezone.utc)),
        ),
    ]
