# Generated by Django 5.0 on 2024-07-06 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_staff_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_full_path',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 45, 50, 268649, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 12, 45, 50, 268670, tzinfo=datetime.timezone.utc)),
        ),
    ]
