# Generated by Django 5.0 on 2024-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
