# Generated by Django 5.0 on 2024-08-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=300, null=True, unique=True),
        ),
    ]
