# Generated by Django 5.0 on 2024-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0003_alter_realestate_number_of_saves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='buying_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='mortgage_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='rent_price',
            field=models.BigIntegerField(),
        ),
    ]
