# Generated by Django 5.0 on 2024-07-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0004_alter_realestate_buying_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealEstateChoices',
            new_name='RealEstateChoice',
        ),
        migrations.RenameModel(
            old_name='RealEstateImages',
            new_name='RealEstateImage',
        ),
    ]
