# Generated by Django 5.0 on 2024-07-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0005_rename_realestatechoices_realestatechoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatechoice',
            name='en_value',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
