# Generated by Django 5.0 on 2024-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0006_realestatechoice_en_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='image_full_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
